name: CI

on:
  push:
    branches: [rebuild-spack]

jobs:
  test:
    name: Spack on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11
        - macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        git clone https://github.com/spack/spack.git
        ./spack/bin/spack -e . concretize
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ~/.spack-ci
        key: ${{ runner.os }}-${{ hashFiles('spack.lock') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install
      run: |
        ./spack/bin/spack -e . install -j3
        ./spack/bin/spack -e . gc -y
