name: CI

on:
  push:
    branches: [rebuild-spack]

jobs:
  build:
    name: Spack on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11
        - macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        git clone --depth 5 https://github.com/spack/spack.git
        patch -p1 -d spack -i ../patches/wrapper.patch
        ./spack/bin/spack -e . concretize
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ~/.spack-ci
        key: ${{ runner.os }}-${{ hashFiles('spack.lock') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install
      run: |
        SPACK_OPTIMIZATION_FLAGS=-Os ./spack/bin/spack -e . install -j3
    - uses: actions/upload-artifact@v2
      with:
        name: spack-binaries-${{ runner.os }}
        path: |
          spack/
          ~/.setup-spack
  upload:
    name: Upload results on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-11
        - macos-10.15
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: spack-binaries-${{ runner.os }}
    - name: Remove garbage
      run: |
        ./spack/bin/spack -e . gc -y