name: Example

on:
  push:
    branches: ['main', 'release/*']
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        - macos-10.15
        ref:
        - develop
        - v0.16.2
        concretizer:
        - original
        - clingo
    
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Set up Spack
        uses: ./
        with:
          os: ${{ matrix.os }}
          ref: ${{ matrix.ref }}
          concretizer: ${{ matrix.concretizer }}
      - run: spack --version
      - run: spack config blame config
      - run: spack --debug install zlib
      - run: which patchelf
